server:
  port: 8081
spring:
  application:
    name: user-service
  cloud:
    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka
        instance:
          prefer-ip-address: true
  datasource:
    username: user
    password: 1234
    url: jdbc:h2:mem:smart_bank_db
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers:
      - localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 5
      retry-backoff-ms: 2000
    consumer:
      group-id: user-events-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: '*'

logging:
  level:
    com.smart.bank: INFO
